### PR TITLE
feat: add gitleaks as pre-commit hook

### PR DESCRIPTION
**Pull request by MartinBernstorff**

### CODE REVIEW

**Review by KennethEnevoldsen — APPROVED** [review]

**Comment by KennethEnevoldsen** [comment]
Why was this auto-merged?

**Comment by KennethEnevoldsen** [comment]
shouldn't @HLasse have approved it as well?

**Comment by MartinBernstorff** [comment]
You approved the changes and I had set auto-merge on :-)

No, the current criterium is for any reviewer to approve the changes.

**Comment by MartinBernstorff** [comment]
I can't find a branch protection that's "wait for all requested reviews to complete". But I think the current setting is fine as well :-)

**Comment by KennethEnevoldsen** [comment]
It is just frustrating to review something that is gonna get auto-merged when another finishes their review. Would change my default behaviour to "wait with review" assuming someone else does it.

**Comment by MartinBernstorff** [comment]
That's a fair point! I shouldn't have enabled auto-merge here 👍

**Pull request merged**
