### PR TITLE
Wrapper to generate features from a dictionary

### PR DESCRIPTION
**Pull request by martbern**
Allow to take a dict and generate prediction features from it.

Ideally, we want the dict to be loadable from json. Since json can only contain primitives, this leaves us with two challenges:

- [x] `predictor_dict` needs to take a df. I tried using an `eval` statement, but the df will be outside of the scope of the `add_predictors_from_dict` method. For now, I pass a dictionary with the dataframes, but this seems inelegant. 

- [x] Since e.g. `resolve_multiple` takes a Callable, we need to resolve the string from the json into a Callable. I'm not sure how we can do that.

- [x] Add catalogue support

This solves #16.

### CODE REVIEW

**Comment by martbern** [comment]
@HLasse, @KennethEnevoldsen, thoughts on how to solve?

**Comment by KennethEnevoldsen** [comment]
Why is this functionality something we want? Why not simply use the `add_predictor` method?

**Comment by martbern** [comment]
1. We might have 100s of features we want to generate. Some of those will be permutations over the same data, e.g.
`last_blood_pressure_within_1_day`, `last_blood_pressure_within_5_days`, `last_blood_pressure_within_90_days`
2. If we have a .json file, we can use that to generate a table for documentation in publications

**Comment by KennethEnevoldsen** [comment]
The type hint for `resolve_multiple` is a "str", which I assume is an error, but I would probably make it:
```
resolve_multiple (Union[str, Callable[...]]): Resolve multiple should be a function which takes .... or a one of the following strings; ..., ..., ..., ... which does ...
```

And then add a dictionary:
```
if isinstance(resolve_multiple, str):
  resolve_multiple = resolve_multiple_fn[resolve_multiple] # fetch from predefined functions
```

You could also use [catalogue](https://pypi.org/project/catalogue/) for this. Basically you simply need to register the function to then be able to fetch it.

**Comment by martbern** [comment]
Great idea with catalogue! Makes it _much_ more elegant, thanks!

**Pull request merged**
